dist: xenial

# command to run tests
script: 
  - wget https://github.com/jgm/pandoc/releases/download/2.7.2/pandoc-2.7.2-1-amd64.deb
  - sudo dpkg -i pandoc-2.7.2-1-amd64.deb
  - pandoc -f markdown -t pptx slides.md -o slides.ppt

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: slides.ppt
  skip_cleanup: true
  on:
    tags: true